// translations.d.ts
// GENERATED by laravel-typed-i18n. Do not edit by hand.

export interface Translations {
  'Hello :name': { name: string | number };
  'Save': {};
  'cart.items': { count: number };
  'messages.profile.updated': {};
  'messages.welcome': { name: string | number };
  'orders.shipped': { count: number; city: string | number };
}

export type TranslationKey = keyof Translations;

export type EmptyParamKeys = {
  [K in TranslationKey]: keyof Translations[K] extends never ? K : never;
}[TranslationKey];
