<?php

declare(strict_types=1);

namespace YuriiDiachuk\LaravelTypedI18n\Generator;

use YuriiDiachuk\LaravelTypedI18n\Parser\TranslationKey;

class TypeScriptGenerator
{
    private const HEADER = <<<'TS'
        // translations.d.ts
        // GENERATED by laravel-typed-i18n. Do not edit by hand.
        TS;

    /**
     * Render a TranslationKey[] into a TypeScript declaration file.
     *
     * Emits an interface mapping each key to its required params, a key union, and a helper
     * type listing param-less keys. Keys are sorted for stable, diff-friendly output.
     *
     * @param  TranslationKey[]  $keys
     */
    public function generate(array $keys): string
    {
        $unique = [];
        foreach ($keys as $key) {
            $unique[$key->key] = $key;
        }

        ksort($unique, SORT_STRING);

        $lines = [
            self::HEADER,
            '',
            'export interface Translations {',
        ];

        foreach ($unique as $key) {
            $lines[] = '  '.$this->quoteKey($key->key).': '.$this->params($key).';';
        }

        $lines[] = '}';
        $lines[] = '';
        $lines[] = 'export type TranslationKey = keyof Translations;';
        $lines[] = '';
        $lines[] = 'export type EmptyParamKeys = {';
        $lines[] = '  [K in TranslationKey]: keyof Translations[K] extends never ? K : never;';
        $lines[] = '}[TranslationKey];';

        return implode("\n", $lines)."\n";
    }

    private function params(TranslationKey $key): string
    {
        $props = [];

        if ($key->isPlural) {
            $props[] = 'count: number';
        }

        foreach ($key->placeholders as $placeholder) {
            $props[] = $placeholder.': string | number';
        }

        if ($props === []) {
            return '{}';
        }

        return '{ '.implode('; ', $props).' }';
    }

    private function quoteKey(string $key): string
    {
        $escaped = addcslashes($key, "'\\");
        $escaped = str_replace(["\n", "\r", "\t", "\0"], ['\n', '\r', '\t', '\0'], $escaped);

        return "'".$escaped."'";
    }
}
